# Generated by Django 5.2 on 2025-04-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
    ]
